{
  "hash": "7f6023167e255e51fbd08c29d65dfe28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistique et informatique appliquées aux sciences sociales\"\nsubtitle: \"L3 Sciences Sociales - Séquence 1\"\nauthor: \"Marc O'Flaherty\"\nformat: \n  revealjs:\n    theme: simple\n    slide-number: c/t\n    lightbox: true\n    chalkboard: true\n    footer: \"Marc O'Flaherty - L3 Sciences Sociales\"\n    echo: true\n---\n\n\n\n\n# 1. Rappel des notions\n*Sur ce que vous avez vu en cours magistral*\n\n## L'Indice de Développement Humain (IDH) {.scrollable}\nPour ce premier excercice, nous disposons d'une base de donnnées issue du Programme des Nations Unies pour le Développement **(PNUD)** avec :  \n\n* **Individus statistiques :** Ce sont les **Pays** (44 dans notre exemple).  \n* **Variables disponibles :**  \n    * *L'IDH*  \n    * *PIB par habitant*  \n    * *Espérance de vie à la naissance*  \n    * *Nombre d'année de scolarisation*  \n    * *Taille de la population*  \n    * *Ratio de palma* (Revenus Top10% / Revenus bottom 40%)  \n    * *ISO 3* (norme de codification cartographique)  \n\n> **Objectif :** Passer d'un tableau de chiffres illisible à des indicateurs clairs et permettre des comparaisons.\n\n\n# 2. Tendance centrale & dispersion\n\n## La Moyenne vs la Médiane {.scrollable}\nComment résumer une distribution en un seul chiffre ?\n\n::: {.columns}\n::: {.column width=\"50%\"}\n### La Moyenne\n* **Calcul :** Somme des valeurs / Nombre de valeurs.  \n* **Qualité :** Rapide, connu; compréhensible.  \n* **Défaut :** Sensible aux extrêmes.  \n    * *Exemple :* Si un milliardaire entre dans un PMU, le \"salaire moyen\" explose.  \n:::\n\n::: {.column width=\"50%\"}\n### La Médiane\n* **Calcul :** La valeur du milieu (50% au-dessus, 50% en-dessous).  \n* **Qualité :** Robuste.  \n* **Défaut :** Plus long à calculer à la main.  \n    * *Exemple :* Le salaire médian du bar ne bouge presque pas pas avec le milliardaire.  \n:::\n:::\n\n## La dispersion : Variance & Écart-type {.scrollable}\nLa moyenne cache la réalité. Voici des outils pour s'en prémunir.  \n\n* **La Variance ($V$) :** C'est la moyenne des carrés des écarts à la moyenne.  \n    * *Utilitée :* C'est une étape mathématique préalable à l'écart-type.  \n    * *Problème :* Difficile à interpréter  \n    \n    \n* **L'Écart-type ($\\sigma$) :** Racine carrée de la variance.  \n    * *Utilité :* On revient à l'unité d'origine.  \n    * *Sens :* C'est l'écart \"moyen\" ou \"typique\" entre les individus.  \n    \n**Un exemple concret :** Nous avons deux classes de terminale (10 élèves).  \n* **Classe A :** 5 élèves ont eu **8/20** et 5 élèves ont eu **12/20**.  \n* **Classe B :** 5 élèves ont eu **5/20** et 5 élèves ont eu **15/20**.  \n\nEst-ce que les moyennes sont les mêmes ?\n\n<details>\n  <summary>Voir les moyennes des classes</summary>\n  \n  Oui, elles sont identiques $\\rightarrow$ 10 de moyenne.\n  \n* **Classe A :** $(5 \\times 8 + 5 \\times 12) = 100$  \n      $100/ 10 = \\mathbf{10}$\n\n* **Classe B :** $(5 \\times 5 + 5 \\times 15) = 100$  \n      $100/ 10 = \\mathbf{10}$\n</details>\n\n**Et la dispersion est-elle la même ?** Calculons la variance et l'écart-type.\n\n<details>\n  <summary>Calcul de la Variance</summary>\n\n  **Formule :** On fait la moyenne des écarts au carré.\n  \n  **Pour la Classe A :**  \n  * Écarts : $8-10 = -2$ et $12-10 = +2$  \n  * Carrés : $(-2)^2 = 4$ et $(2)^2 = 4$  \n  * Variance : $(5 \\times 4 + 5 \\times 4) = 40$  \n    $40/ 10 = \\mathbf{4}$  \n\n  **Pour la Classe B :**  \n  * Écarts : $5-10 = -5$ et $15-10 = +5$  \n  * Carrés : $(-5)^2 = 25$ et $(5)^2 = 25$  \n  * Variance : $(5 \\times 25 + 5 \\times 25) = 250$  \n    $250/ 10 = \\mathbf{25}$  \n</details>\n\n<details>\n  <summary>Résultats (Écart-type) et Interprétation</summary>\n\n  Pour revenir à une note sur 20, on prend la racine carrée ($\\sqrt{V}$).  \n\n* **Classe A :** $\\sigma = \\sqrt{4} = \\mathbf{2}$  \n  \n* **Classe B :** $\\sigma = \\sqrt{25} = \\mathbf{5}$  \n\n  **Conclusion :**  \n  Bien que la moyenne soit la même (10/20), la **Classe B** est beaucoup plus hétérogène (plus dispersée) que la **Classe A** qui est plus homogène.  \n  \n  En moyenne, dans la classe B, les élèves sont à 5 points de la moyenne, contre seulement 2 points dans la classe A.  \n</details>\n\n\n\n## Les Quantiles {.scrollable}  \nPour voir les inégalités, on découpe la population en parts égales.  \n\n* **Quartiles (4 parts) :**  \n    * Q1 : Les 25% les plus pauvres.  \n    * Q2 (Médiane) : 50% de la population gagne moins, 50% gagne plus.  \n    * Q3 : Les 75% (le seuil d'entrée des 25% les plus riches).  \n* **Déciles (10 parts) :** D1 (les 10% les plus pauvres) à D9.  \n\n| Quantile | Secteur privé (€) | Fonction publique (€) |\n| :--- | :---: | :---: |\n| **1ᵉʳ décile (D1)** | 1 510 | 1 670 |\n| **1ᵉʳ quartile (Q1)** | 1 740 | 1 950 |\n| **Médiane (Q2)** | 2 180 | 2 380 |\n| **3ᵉ quartile (Q3)** | 2 990 | 2 990 |\n| **9ᵉ décile (D9)** | 4 300 | 3 800 |\n  \n<details>\n  <summary>Comment lire ce tableau ?</summary>\n\n  **Lecture stricte (à connaître pour le partiel) :**  \n  \n  * **Pour D1 (Privé) :** \"10 % des salariés du secteur privé gagnent **moins de** 1 510 euros nets par mois.\" (On peut aussi dire : \"90 % gagnent plus\").  \n  * **Pour la Médiane (Public) :** \"La moitié des agents du public gagne moins de 2 380 euros, l'autre moitié gagne plus.\"  \n  * **Pour D9 (Privé) :** \"90 % des salariés gagnent moins de 4 300 euros.\" (Ou : \"Les 10 % les mieux payés gagnent **plus de** 4 300 euros\").  \n\n  **Observation sociologique :**\n  On remarque que les bas salaires sont mieux rémunuérés dans le public (D1 public > D1 privé), mais que les très hauts salaires s'envolent dans le privé (D9 privé > D9 public).  \n\n\n*(Source : [Insee, Dispersion des salaires nets mensuels en équivalent temps plein en 2023](https://www.insee.fr/fr/statistiques/7457170#tableau-figure3))*  \n</details>\n\n# 3. La visualisation graphique (dataviz)\n\n## La boîte à moustache (Boxplot) {.scrollable}\n\nUn résumé visuel de 5 informations clés.\n\n* La **Boîte** contient 50% des salariés (l'écart inter-quartile).\n* La **Barre** au milieu est la médiane.\n* Les **Moustaches** vont ici jusqu'aux déciles (D1 et D9) pour voir les extrêmes.\n\n\n\n\n\n::: {.cell output-location='default' lightbox='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Voir le code R\"}\nlibrary(ggplot2)\n\n# 1. On crée la \"DB\" (le petit tableau de données) manuellement\ndf_salaires <- data.frame(\n  Secteur = c(\"Secteur Privé\", \"Fonction Publique\"),\n  D1      = c(1510, 1670),  \n  Q1      = c(1740, 1950),  \n  Mediane = c(2180, 2380),  \n  Q3      = c(2990, 2990),  \n  D9      = c(4300, 3800)   \n)\n\n# 2. On génère le graphique\nggplot(df_salaires, aes(x = Secteur, fill = Secteur)) +\n  geom_boxplot(\n    aes(ymin = D1, lower = Q1, middle = Mediane, upper = Q3, ymax = D9),\n    stat = \"identity\",  \n    width = 0.5         \n  ) +\n  scale_fill_manual(values = c(\"#404080\", \"#C04657\")) + \n  labs(\n    title = \"Dispersion des salaires (Nets mensuels)\",\n    y = \"Euros (€)\",\n    x = \"\",\n    caption = \"Source : Insee 2023\"\n  ) +\n  \n  scale_y_continuous(labels = scales::label_number(big.mark = \" \")) + # Séparateur de milliers\n  \n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Dispersion des salaires](slides_seq1_files/figure-revealjs/fig-salaires-1.png){#fig-salaires width=864}\n:::\n:::\n\n\n\n\n\n## L'Histogramme {.scrollable}\n\n**Le principe des \"Classes\" :**\n\nPour résumer l'information, on regroupe les pays par paquets (ici des tranches de 5 ans).\n\n* **L'axe horizontal :** L'espérance de vie.  \n* **L'axe vertical :** Le nombre de pays dans cette tranche.  \n* **La forme :** Avec 183 pays, on voit une inégalité pour l'espérance de vie.  \n\n\n\n\n::: {.cell lightbox='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Voir le code R\"}\nlibrary(ggplot2)\n\n# 1. Données\ndf_pays <- data.frame(\n  Esp_Vie = c(\n    83.7, 83.4, 83.1, 82.8, 82.8, 82.7, 82.7, 82.5, 82.4, 82.4, \n    82.3, 82.2, 82.0, 81.9, 81.81, 81.8, 81.7, 81.6, 81.5, 81.4, \n    81.2, 81.1, 81.0, 81.0, 80.8, 80.6, 80.5, 80.5, 79.6, 79.1, \n    79.1, 78.8, 78.5, 78.2, 78.1, 78.0, 77.8, 77.8, 77.7, 77.6, \n    77.5, 77.4, 77.1, 77.0, 76.9, 76.7, 76.7, 76.6, 76.4, 76.3, \n    76.2, 76.2, 76.1, 76.1, 76.1, 76.0, 75.9, 75.8, 75.7, 75.6, \n    75.6, 75.5, 75.5, 75.5, 75.3, 75.2, 75.0, 75.0, 75.0, 74.9, \n    74.9, 74.9, 74.8, 74.8, 74.8, 74.7, 74.6, 74.6, 74.6, 74.5, \n    74.5, 74.4, 74.3, 74.1, 74.1, 74.0, 74.0, 73.9, 73.6, 73.6, \n    73.5, 73.5, 73.3, 73.2, 73.2, 72.7, 72.7, 72.3, 72.1, 72.0, \n    71.9, 71.8, 71.6, 71.3, 71.2, 71.1, 70.9, 70.7, 70.6, 70.5, \n    70.2, 70.1, 69.9, 69.8, 69.7, 69.4, 69.4, 69.2, 69.2, 69.1, \n    68.9, 68.8, 68.7, 68.5, 68.3, 68.3, 67.5, 66.7, 66.6, 66.4, \n    66.3, 66.3, 66.2, 66.1, 66.0, 65.8, 65.7, 65.7, 65.7, 65.5, \n    64.8, 64.7, 64.7, 64.5, 64.1, 63.5, 63.5, 63.5, 63.4, 63.1, \n    62.9, 62.9, 62.4, 62.3, 61.8, 61.8, 61.8, 61.4, 61.1, 60.7, \n    60.5, 60.0, 59.9, 59.9, 59.8, 59.6, 59.0, 58.9, 58.9, 58.3, \n    58.2, 58.2, 57.6, 57.3, 57.3, 55.0, 54.5, 53.7, 53.3, 53.1, \n    52.5, 52.4, 50.1\n  )\n)\n\n# 2. Histogramme avec bornes strictes\nggplot(df_pays, aes(x = Esp_Vie)) +\n  geom_histogram(\n    breaks = seq(50, 85, 5), # On impose les coupures : 50, 55, 60...\n    closed = \"left\",        # [50, 55[ (50 inclus, 55 exclu) - Un standard en démographie\n    \n    fill = \"#404080\",       \n    color = \"white\",\n    alpha = 0.8\n  ) +\n  labs(\n    y = \"Nombre de pays\",\n    x = \"Espérance de vie (années)\",\n    title = \"Répartition mondiale (OMS 2015)\"\n  ) +\n  theme_minimal() +\n  # Légende de l'ordonnée\n  scale_y_continuous(breaks = seq(0, 60, 10)) +\n  \n  # Légende de l'abscisse X :\n  scale_x_continuous(breaks = seq(50, 85, 5))\n```\n\n::: {.cell-output-display}\n![Distribution mondiale de l'espérance de vie (183 pays, OMS 2015)](slides_seq1_files/figure-revealjs/fig-histo-1.png){#fig-histo width=960}\n:::\n:::\n\n\n\n\n\n\n# 4. Statistiques bivariées\n*Comprendre le lien entre deux phénomènes*\n\n## Le Nuage de points (Scatterplot) {.scrollable}\nAvant de calculer, il faut **regarder**.\nPosons-nous la question : *\"Est-ce que l'argent fait le bonheur (ou du moins la santé) ?\"*\n\n* **Axe X (Horizontal) :** La richesse (PIB/habitant).\n* **Axe Y (Vertical) :** La santé (Espérance de vie).\n* **Chaque point** est un pays.\n\n\n\n\n::: {.cell lightbox='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Voir le code R\"}\n# Création d'un jeu de données fictif mais réaliste pour l'exemple\ndf_demo <- data.frame(\n  Pays = c(\"Pays A\", \"Pays B\", \"Pays C\", \"Pays D\", \"Pays E\", \"Pays F\"),\n  PIB = c(500, 2000, 15000, 35000, 48000, 75000),\n  Esp_Vie = c(52, 61, 74, 79, 82, 84)\n)\n\nlibrary(ggplot2)\n\nggplot(df_demo, aes(x = PIB, y = Esp_Vie)) +\n  geom_point(size = 4, color = \"#404080\") +\n  geom_text(aes(label = Pays), vjust = -1, size = 3) + # Ajout des noms\n  scale_x_continuous(labels = scales::label_number(big.mark = \" \")) +\n  labs(title = \"Lien entre Richesse et Santé\", \n       x = \"Richesse ($/hab)\", y = \"Espérance de vie (ans)\") +\n  theme_minimal() +\n  ylim(50, 90)\n```\n\n::: {.cell-output-display}\n![Exemple de nuage de points](slides_seq1_files/figure-revealjs/fig-nuage-1.png){#fig-nuage width=960}\n:::\n:::\n\n\n\n\n<details> \n<summary>Qu'est-ce qu'on observe ?</summary>\n\nOn voit que les points ne sont pas mis au hasard. Ils forment une \"banane\" ou une ligne qui \"monte\".\n\nTendance : Plus on va vers la droite (riche), plus on monte (vieux).\n\nConclusion visuelle : Il y a une corrélation positive $\\rightarrow$ plus un pays est riche, plus l'espérance de vie moyenne des habitant sy est élevé.\n\n</details>\n\n\n## La Corrélation ($r$) {.scrollable}\nLe nuage nous donne la forme, la corrélation nous donne la **force**.\n\nC'est une note comprise entre **-1** et **+1**.\n\n::: {.columns}\n::: {.column width=\"50%\"}\n### $r \\approx 0$ (Le chaos)\nLe nuage ressemble à une \"patate\". Connaître le PIB ne nous aide pas à deviner l'espérance de vie.\n:::\n\n::: {.column width=\"50%\"}\n### $r \\rightarrow 1$ (La ligne parfaite)\nLe nuage est très fin, comme un cigare. Si je connais votre PIB, je peux deviner votre espérance de vie avec précision.\n:::\n:::\n\n> **Ici :** Pour le lien PIB/Espérance de vie, le $r$ est souvent autour de **0.70**. C'est un lien fort !\n\n## La Régression Linéaire : La \"Machine à prédiction\" {.scrollable}\nOn ne veut plus juste constater le lien, on veut le **modéliser** pour faire des prévisions.\nOn trace une droite qui passe \"au milieu\" du nuage.\n\nC'est l'équation : $Y = a \\cdot X + b$\n\nMais parlons français :\n$$Espérance = (Pente \\times Richesse) + Socle$$\n\n* **La Pente ($a$) :** C'est le \"taux de conversion\".\n    * *Question :* \"Si je donne 1000$ de plus à ce pays, combien de mois de vie il gagne ?\"\n* **L'Ordonnée à l'origine ($b$) :** Le point de départ.\n    * *Question :* \"Quelle serait l'espérance de vie d'un pays avec 0$ de PIB ?\"\n\n\n\n\n::: {.cell lightbox='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Voir la droite magique\"}\n# Note : df_demo doit avoir été créé dans la slide précédente\n# Si besoin, décommentez les lignes ci-dessous :\n# df_demo <- data.frame(Pays = c(\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"), PIB = c(500, 2000, 15000, 35000, 48000, 75000), Esp_Vie = c(52, 61, 74, 79, 82, 84))\n\nlibrary(ggplot2)\n\nggplot(df_demo, aes(x = PIB, y = Esp_Vie)) +\n  geom_point(size = 4, color = \"#404080\") +\n  # C'est cette ligne qui ajoute la régression linéaire (method = lm)\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#C04657\", size = 1.5) +\n  scale_x_continuous(labels = scales::label_number(big.mark = \" \")) +\n  labs(title = \"La droite de régression (Le modèle)\", \n       x = \"Richesse ($/hab)\", y = \"Espérance de vie (ans)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Exemple de droite de corrélation](slides_seq1_files/figure-revealjs/fig-reg-1.png){#fig-reg width=960}\n:::\n:::\n\n\n\n\n<details>\n  <summary>Exemple de lecture</summary>\n  \n  **Imaginons que le logiciel nous donne l'équation :**\n  $$Y = 0.0004X + 55$$\n\n  * **1. Le socle ($b=55$) :**\n      Même sans économie (PIB = 0), dans ce modèle théorique, l'humain vit environ **55 ans** (c'est le \"niveau de base\").\n\n  * **2. L'effet richesse ($a=0.0004$) :**\n      Le coefficient est tout petit car 1 dollar pèse peu.\n      Concrètement : Pour gagner **1 an** d'espérance de vie, il faut augmenter le PIB de **2 500 $**.\n      *(Calcul : $1 / 0.0004 = 2500$)*.\n\n  ---\n  **À quoi ça sert ?**\n  Si un pays découvre du pétrole et s'enrichit (+ 10 000 $ de PIB), on peut **prédire** que son espérance de vie augmentera de 4 ans.\n</details>\n\n\n## Fin de la séquence 1",
    "supporting": [
      "slides_seq1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}